theme: "jekyll-theme-midnight"
title: "Le monde de Joël J. Présent"
description: "Joël J. Présent's GitHub page"
baseurl: "/"
markdown: "GFM"

github_username: "JoelJPresent"
linkedin_username: "joeljpresent"
twitter_username: "JoelJPresent"

sass:
    sass_dir: _sass
